### ISSUE TITLE
unable to resolve dependency tree when installing

### ISSUE THREAD

**Issue by imarotte** [marc-ed-raffalli/apollo-hooks-extended#4]
Tried to install for the first time. It did not like that I am using react 17.0.2

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: customerclient@0.0.1-4
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!   peerOptional react@"^16.8.0 || ^17.0.0" from @apollo/client@3.3.14
npm ERR!   node_modules/@apollo/client
npm ERR!     @apollo/client@"^3.3.8" from the root project
npm ERR!     peer @apollo/client@"^3.0.0" from apollo-hooks-extended@1.0.0
npm ERR!     node_modules/apollo-hooks-extended
npm ERR!       apollo-hooks-extended@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from apollo-hooks-extended@1.0.0
npm ERR! node_modules/apollo-hooks-extended
npm ERR!   apollo-hooks-extended@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by marc-ed-raffalli** [comment]
Indeed, just checked `@apollo/client` https://github.com/apollographql/apollo-client/blob/main/package.json, the `peerDependencies ` is `"react": "^16.8.0 || ^17.0.0"`
Thanks for reporting it, will do a release in the next few hours

**Comment by marc-ed-raffalli** [comment]
@imarotte, is the issue resolved?

**Comment by marc-ed-raffalli** [comment]
Closing the issue, feel free to reopen it.
